databaseChangeLog:
  -  changeSet:
       id: create_leave_applications_table_845c6
       author: saif
       changes:
         -  createTable:
              tableName: leave_application
              columns:
                -  column:
                     name: id
                     type: int
                     autoIncrement: true
                     constraints:
                       primaryKey: true
                       nullable: false
                - column:
                    name: date_from
                    type: dateTime
                    constraints:
                      nullable: false
                - column:
                    name: date_to
                    type: dateTime
                    constraints:
                      nullable: false
                - column:
                    name: student_id
                    type: int
                    constraints:
                      foreignKeyName: fk_leave_application_student_id
                      references: student(id)
                      nullable: false
                - column:
                    name: application_body
                    type: varchar(1000)
                    constraints:
                      nullable: false
                - column:
                    name: supported_document_name
                    type: varchar(30)
                - column:
                    name: supported_document_type
                    type: varchar(30)
                - column:
                    name: supported_document_size
                    type: varchar(20)
                - column:
                    name: supported_document_base64
                    type: varchar(4000)
                - column:
                    name: status
                    type: varchar(10)
                    constraints:
                      nullable: false
                - column:
                    name: decision_by_id
                    type: int
                    constraints:
                      foreignKeyName: fk_leave_application_decision_by
                      references: teacher(id)